### ISSUE TITLE
ComfyUI-CogVideoX-MZ ( import Failed - no module named "timm"  )

### ISSUE THREAD

**Issue by KeeeeperOfTheLight** [MinusZoneAI/ComfyUI-CogVideoX-MZ#15]
hello Sir.
I'm having this issue.
can you help me please.

![cogvideo3](https://github.com/user-attachments/assets/8dd05742-4fae-459d-9877-248963beba3c)

![cogvideo2](https://github.com/user-attachments/assets/a2146b10-3081-433a-879f-b62b44d561d3)

![cogvideo](https://github.com/user-attachments/assets/46191a1b-e290-4f8b-8942-fa7a2058f626)

**Comment by wailovet** [comment]
Have you updated kijai/ComfyUI-CogVideoXWrapper to the latest version?

**Comment by KeeeeperOfTheLight** [comment]
i had the same issue in CogVideoXWrapper node in this link

https://github.com/kijai/ComfyUI-CogVideoXWrapper/issues/93

but the owner change some things in the node and the problem solved when i updated the node.

i tried to update, fix or reinstall and nothing works.

**Comment by wailovet** [comment]
I just did the same treatment. You can try to update this node to the latest version and give it a try.

**Comment by KeeeeperOfTheLight** [comment]
> I just did the same treatment. You can try to update this node to the latest version and give it a try.

thank you so much sir it worked ❤️
